In [2]:
print("hello world ")
for i in range(10):
    print(i)


hello world 
0
1
2
3
4
5
6
7
8
9


In [2]:
import numpy as np 

In [6]:
arr=np.array([1,22,34,56])
print(arr)
print(type(arr))
a=[1,22,34,56]
print(a ,type(a))

[ 1 22 34 56]
<class 'numpy.ndarray'>
[1, 22, 34, 56] <class 'list'>


In [8]:
arr1=np.array([1,2,3 ,"false",True])
print(arr1)

['1' '2' '3' 'false' 'True']


In [11]:
#convert list into array
arr2=np.array(a)
print(arr2, type(arr2))

[ 1 22 34 56] <class 'numpy.ndarray'>


In [15]:
print(a)
arr.reshape(2,2)
arr.shape


[1, 22, 34, 56]


(4,)

In [18]:

arr=np.linspace(0,10,5)
print(arr)
a= np.random.rand(23)
print(a)

[ 0.   2.5  5.   7.5 10. ]
[0.07457458 0.68370328 0.73879742 0.69290876 0.2957106  0.40601591
 0.01898495 0.32912358 0.13593661 0.9459009  0.88034499 0.44362511
 0.64606443 0.49235577 0.37336964 0.96788358 0.00748071 0.37128792
 0.60314563 0.43007059 0.11835309 0.74638099 0.91941965]


In [21]:
arr=np.arange(1,31).reshape(6,5)
print(arr)
print(arr.shape)
print(arr.size)
print(arr.dtype)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
(6, 5)
30
int64


In [23]:
print(arr.min())
print(arr.max())
print(arr.sum())


1
30
465


In [27]:
print(np.sum(arr,axis=1))
print(np.sum(arr, axis=0))

[ 15  40  65  90 115 140]
[ 81  87  93  99 105]


In [30]:
print(arr.std())
print(arr.argmax())
print(arr.argmin())

8.65544144839919
29
0


In [32]:
a= np.arange(1,31).reshape(6,5)
slice=a[3:,3:]
print(slice)

[[19 20]
 [24 25]
 [29 30]]


In [33]:
print(a[1,2])
print(a[:,2])

8
[ 3  8 13 18 23 28]


In [34]:
arr=np.arange(1,41)
value=arr%2==0
print(arr[value])


[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]


In [35]:
v=arr%2==1
print(arr[v])

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39]
