In [1]:
import numpy as np

In [2]:
a1=np.array([10,20,30,40,50])

a2=np.array([60,70,80,90,10])
a2

array([60, 70, 80, 90, 10])

In [4]:
print(a1+a2)
print(a1-a2)
print(a1*a2)
print(a1/a2)
print(a1//a2)
print(a1**a2)


[ 70  90 110 130  60]
[-50 -50 -50 -50  40]
[ 600 1400 2400 3600  500]
[0.16666667 0.28571429 0.375      0.44444444 5.        ]
[0 0 0 0 5]
[1152921504606846976                   0                   0
                   0   97656250000000000]


In [5]:
#broadcasting
arr=np.array([1,2,3,4,5])
arr+20

array([21, 22, 23, 24, 25])

In [6]:
arr*100


array([100, 200, 300, 400, 500])

In [8]:
arr1=np.arange(1,31).reshape(6,5)
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [10]:
arr2=arr1+20
arr2

array([[21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [15]:
#deep copy &shallow copy 
a= np.array([10,20,30,40,50])
a

array([10, 20, 30, 40, 50])

In [12]:
b=a
print(b)

[10 20 30 40 50]


In [13]:
b=a.view()
b

array([10, 20, 30, 40, 50])

In [16]:
b=a.view()
b[0]=99
print(b,"shallow copy")
print(a,"original content")

[99 20 30 40 50] shallow copy
[99 20 30 40 50] original content


In [17]:
arr1=np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [18]:
arr2=arr1.copy() #deep copy 
arr2[0]=99


In [19]:
print(arr2,"deep copy")
print(arr1,"original content")

[99  2  3  4  5] deep copy
[1 2 3 4 5] original content


In [22]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [23]:
#advance array manipulation 
N=np.array([1,2,3,4])
Q=np.array([6,7,8,9])
Q

array([6, 7, 8, 9])

In [24]:
np.vstack(( N,Q))

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [25]:
np.hstack(( N,Q))

array([1, 2, 3, 4, 6, 7, 8, 9])

In [28]:
np.dstack((N,Q))

array([[[1, 6],
        [2, 7],
        [3, 8],
        [4, 9]]])

In [27]:
np.column_stack((N,Q))

array([[1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [29]:
w=np.arange(16).reshape(4,4)
w

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [30]:
np.hsplit(w,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [35]:
np.vsplit(w,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]