In [21]:
import numpy as np 

In [22]:
a=np.array([10,20,30,40])
b=np.array([50,60,70,80])
c=a+b
print(c)
print(a-b)
print(a*b)
print(a/b)
print(a//b)
print(a**b)

[ 60  80 100 120]
[-40 -40 -40 -40]
[ 500 1200 2100 3200]
[0.2        0.33333333 0.42857143 0.5       ]
[0 0 0 0]
[-5376172055173529600                    0                    0
                    0]


In [23]:
import numpy as np

A = np.array([[1, 2],[3, 4]])

B = np.array([[5, 6],[7, 8]])

print(A + B)


[[ 6  8]
 [10 12]]


In [24]:
#broadcasting questions 
C=np.array([10,20]) #concept of automatic shape expansion
print(A+C)

[[11 22]
 [13 24]]


In [25]:
#operation between array &scaalr 
print(B*2)
#operation between different shaped arrays 
print(B+C)

[[10 12]
 [14 16]]
[[15 26]
 [17 28]]


In [26]:
a=np.array([[1,2,3],[4,5,6]])
n=np.array([10,20,30])
print(a+n) #row wise 
b=np.array([[10],[20]])
print(a+b) #column wise 

[[11 22 33]
 [14 25 36]]
[[11 12 13]
 [24 25 26]]


In [27]:
d=np.dot(a,n)
d

array([140, 320])

In [28]:
c=b.view()
print(c,"shallow copy")
print(b,"original data ")

[[10]
 [20]] shallow copy
[[10]
 [20]] original data 


In [29]:
e=c.copy()
e[0]=45
print(e,"deep copy")
print(c,"original data")

[[45]
 [20]] deep copy
[[10]
 [20]] original data


In [30]:

arr = np.array([1, 2, 3, 4, 5])
sliced = arr[1:4]   # slicing
print(arr)
print(sliced)      

sliced[0] = 99
print(arr)          # [1 99 3 4 5]  ← original भी बदल गया


[1 2 3 4 5]
[2 3 4]
[ 1 99  3  4  5]


In [31]:
#matrix multiplication 
a=np.array([[1,2,3],[4,5,6]])
b=np.array([11,20,30])
c=np.dot(a,b)
print(c)

[141 324]


In [32]:
print(a*b,"element wise")
print(c,"matrix multiplication ")

[[ 11  40  90]
 [ 44 100 180]] element wise
[141 324] matrix multiplication 


In [33]:
print(a.T,"transpose") #row column interchange 

[[1 4]
 [2 5]
 [3 6]] transpose


In [34]:
#linear algebra operations 
a=np.array([[1,2,3],[4,5,6]])
b=np.array([11,20,30])
c=np.linalg.vecdot(a,b)
print(c)

[141 324]


In [35]:
#array stacking 
#vertical stacking 
a=np.array([[1,2,3],[4,5,6]])
b=np.array([11,20,30])
c=np.vstack((a,b))
print(c)


[[ 1  2  3]
 [ 4  5  6]
 [11 20 30]]


In [36]:
#horizontal stacking 
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[11,20,30],[13,14,15]])
c=np.hstack((a,b))
print(c)

[[ 1  2  3 11 20 30]
 [ 4  5  6 13 14 15]]


In [37]:
d=np.column_stack((a,b)) #column stacking 
d

array([[ 1,  2,  3, 11, 20, 30],
       [ 4,  5,  6, 13, 14, 15]])

In [38]:
e=np.dstack((a,b))#depth or dimension alignmnet stacking
e

array([[[ 1, 11],
        [ 2, 20],
        [ 3, 30]],

       [[ 4, 13],
        [ 5, 14],
        [ 6, 15]]])

In [ ]:
#array splitting 
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[11,20,30],[13,14,15]]) #row or horizontal splitting 
c=np.hsplit(a,3)
c

[array([[1],
        [4]]),
 array([[2],
        [5]]),
 array([[3],
        [6]])]

In [ ]:
d=np.vsplit(b,2) #column or vertical splitting 
d

[array([[11, 20, 30]]), array([[13, 14, 15]])]

In [ ]:
e=np.split(a,2) #dividing into equal parts
e

[array([[1, 2, 3]]), array([[4, 5, 6]])]