In [1]:
import numpy as np

In [2]:
arr=np.arange(1,31).reshape(6,5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [3]:
print(arr[0])#extract 1st row
print(arr[-1])#extract last row
print(arr[:,2])#extract 3rd column
print(arr[0:3])#extract first 3 rows 
print(arr[-3:])#extract last 3 rows 
print(arr[:,0:2])#extract first 2 columns 

[1 2 3 4 5]
[26 27 28 29 30]
[ 3  8 13 18 23 28]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
[[ 1  2]
 [ 6  7]
 [11 12]
 [16 17]
 [21 22]
 [26 27]]


In [4]:
print(arr[:,-2:])#extract last two columns
print(arr[0:3,1:5])#extract rows from 1 to 3 and columns from 2 to 4
print(arr[1:])#extract rows from 2nd till last 
print(arr[:,2:])#extract columns from 3 
print(arr[::2,]) #extract every 2nd row 
print(arr[:,::2]) #extract every 2nd column

[[ 4  5]
 [ 9 10]
 [14 15]
 [19 20]
 [24 25]
 [29 30]]
[[ 2  3  4  5]
 [ 7  8  9 10]
 [12 13 14 15]]
[[ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]
 [18 19 20]
 [23 24 25]
 [28 29 30]]
[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [21 22 23 24 25]]
[[ 1  3  5]
 [ 6  8 10]
 [11 13 15]
 [16 18 20]
 [21 23 25]
 [26 28 30]]


In [5]:
print(arr[-3:,-2:])  # extract bottom right 3x2 matrix
print(arr[0:4,0:3])  # extract top left 4x3 matrix
print(arr[::-1])     # reversing order of rows 
print(arr[:,::-1])   # reversing order of columns
print(arr[::-1,::-1])# reversing both rows & columns
print(arr[1:4,1:4])  # extracting center submatrix
print(arr[[0,-1], :])# extracting first and last rows only 
print(arr[:, [0,-1]])# extracting first and last columns only
print(arr[0:4,0:3])#extarct top left 4X3 matrix
print(arr[::-1])#reversing order of rows 
print(arr[:,::-1])#reversing order of columns
print(arr[::-1,::-1])#reversing both rows & columns
print(arr[1:4,1:4])# extracting middle 2X3 matrix 


[[19 20]
 [24 25]
 [29 30]]
[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]
 [16 17 18]]
[[26 27 28 29 30]
 [21 22 23 24 25]
 [16 17 18 19 20]
 [11 12 13 14 15]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]
[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]
 [20 19 18 17 16]
 [25 24 23 22 21]
 [30 29 28 27 26]]
[[30 29 28 27 26]
 [25 24 23 22 21]
 [20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]
[[ 1  2  3  4  5]
 [26 27 28 29 30]]
[[ 1  5]
 [ 6 10]
 [11 15]
 [16 20]
 [21 25]
 [26 30]]
[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]
 [16 17 18]]
[[26 27 28 29 30]
 [21 22 23 24 25]
 [16 17 18 19 20]
 [11 12 13 14 15]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]
[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]
 [20 19 18 17 16]
 [25 24 23 22 21]
 [30 29 28 27 26]]
[[30 29 28 27 26]
 [25 24 23 22 21]
 [20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [6]:
print(arr[0,-1])#extracting first and last rows only 
print(arr[:,0])#extracting first and last columns only


5
[ 1  6 11 16 21 26]


In [7]:
print(arr[1::2])#extracting all odd indexed rows 
print(arr[:,::2])#extracting odd indexed columns
print(arr[4,2])#extract element at row index 4 and column index 2 
print(arr[3])#extacting entire row containing element 18
print(arr[:,3])#extracting entire column containing  value  14

[[ 6  7  8  9 10]
 [16 17 18 19 20]
 [26 27 28 29 30]]
[[ 1  3  5]
 [ 6  8 10]
 [11 13 15]
 [16 18 20]
 [21 23 25]
 [26 28 30]]
23
[16 17 18 19 20]
[ 4  9 14 19 24 29]


In [8]:
print(arr[[0,-1],[0,-1]])#extracting 4 corner elements 
print(arr[:,2:3])#extracting centre column only
print(arr[:,arr.shape[1]//2])

[ 1 30]
[[ 3]
 [ 8]
 [13]
 [18]
 [23]
 [28]]
[ 3  8 13 18 23 28]


In [9]:
print(arr[1:4,::2]) #extracting rows 1 to 4 & every second column
print(arr[:,1:4])#extracting every row but with columns index 1 to 3 
print(arr[1:4,1:4])#extract 2X2 block from centre of array

[[ 6  8 10]
 [11 13 15]
 [16 18 20]]
[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]
 [17 18 19]
 [22 23 24]
 [27 28 29]]
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]
